FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN apk update && apk add --no-cache python3 make g++

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]