services:
  postgres:
    image: postgres:15
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  redis:
    image: redis:7
    container_name: dev_redis
    ports:
      - "6379:6379"
    networks:
      - dev-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: dev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - dev-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: dev_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dev-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: dev_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker inside Jenkins
    networks:
      - dev-network

volumes:
  postgres_data:
  jenkins_home:

networks:
  dev-network: